export const likedSongs = [
  {
    id: 1,
    title: "Blinding Lights",
    artist: "The Weeknd",
    url: "./songs/lofi.mp3",
    thumbnail: "./thumbnails/aesthetic.png",
  },
  {
    id: 2,
    title: "Shape of You",
    artist: "Ed Sheeran",
    url: "./songs/lost.mp3",
    thumbnail: "./thumbnails/artists.png",
  },
  {
    id: 3,
    title: "Levitating",
    artist: "Dua Lipa",
    url: "./songs/gardens.mp3",
    thumbnail: "./thumbnails/DreamOn.png",
  },
  {
    id: 4,
    title: "Someone Like You",
    artist: "Adele",
    url: "./songs/lofi.mp3",
    thumbnail: "./thumbnails/Believer.png",
  },
  {
    id: 5,
    title: "Bad Guy",
    artist: "Billie Eilish",
    url: "./songs/lost.mp3",
    thumbnail: "./thumbnails/Dragons.png",
  },
  {
    id: 6,
    title: "Believer",
    artist: "Imagine Dragons",
    url: "./songs/gardens.mp3",
    thumbnail: "./thumbnails/Shortwave.png",
  },
  {
    id: 7,
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    url: "./songs/lofi.mp3",
    thumbnail: "./thumbnails/aesthetic.png",
  },
  {
    id: 8,
    title: "Stay",
    artist: "The Kid LAROI & Justin Bieber",
    url: "./songs/lost.mp3",
    thumbnail: "./thumbnails/artists.png",
  },
  {
    id: 9,
    title: "Closer",
    artist: "The Chainsmokers ft. Halsey",
    url: "./songs/gardens.mp3",
    thumbnail: "./thumbnails/DreamOn.png",
  },
  {
    id: 10,
    title: "Senorita",
    artist: "Shawn Mendes & Camila Cabello",
    url: "./songs/lofi.mp3",
    thumbnail: "./thumbnails/Believer.png",
  },
  {
    id: 11,
    title: "Perfect",
    artist: "Ed Sheeran",
    url: "./songs/lost.mp3",
    thumbnail: "./thumbnails/DreamOn.png",
  },
  {
    id: 12,
    title: "Memories",
    artist: "Maroon 5",
    url: "./songs/gardens.mp3",
    thumbnail: "./thumbnails/Dragons.png",
  },
  {
    id: 13,
    title: "Counting Stars",
    artist: "OneRepublic",
    url: "./songs/lofi.mp3",
    thumbnail: "./thumbnails/artists.png",
  },
  {
    id: 14,
    title: "Dance Monkey",
    artist: "Tones and I",
    url: "./songs/lost.mp3",
    thumbnail: "./thumbnails/Shortwave.png",
  },
  {
    id: 15,
    title: "Love Yourself",
    artist: "Justin Bieber",
    url: "./songs/gardens.mp3",
    thumbnail: "./thumbnails/aesthetic.png",
  },
  {
    id: 16,
    title: "Faded",
    artist: "Alan Walker",
    url: "./songs/lofi.mp3",
    thumbnail: "./thumbnails/DreamOn.png",
  },
  {
    id: 17,
    title: "Thunder",
    artist: "Imagine Dragons",
    url: "./songs/lost.mp3",
    thumbnail: "./thumbnails/Shortwave.png",
  },
  {
    id: 18,
    title: "Havana",
    artist: "Camila Cabello",
    url: "./songs/gardens.mp3",
    thumbnail: "./thumbnails/artists.png",
  },
  {
    id: 19,
    title: "Let Me Love You",
    artist: "DJ Snake ft. Justin Bieber",
    url: "./songs/lofi.mp3",
    thumbnail: "./thumbnails/Dragons.png",
  },
  {
    id: 20,
    title: "Photograph",
    artist: "Ed Sheeran",
    url: "./songs/lost.mp3",
    thumbnail: "./thumbnails/Shortwave.png",
  },
];
